name: mobx_estudos_flutter
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^5.0.0
  get_it: ^6.0.0
dev_dependencies:
  build_runner: ^1.10.0
  mobx_codegen: ^1.1.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true